### ISSUE TITLE
[SECURITY] It's quite easy to circumvent the check

### ISSUE THREAD

**Issue by GenieTim** [gruessung/php-gfont-proxy#2]
Your check for whether it's a Google URL is pretty easy to circumvent. 

Example:

https://fonts.your-domain.com/index.php?url=https://my-malicious-url.com?fonts.googleapis.com

I think this is a critical bug, as it allows your (potentially trustworthy) domain to be misused for being a proxy to any page, including using a non-https page to be served on your https page.

**Comment by gruessung** [comment]
You're right. Thanks for your report. I'll fix that.

**Comment by gruessung** [comment]
@GenieTim  I changed the check line to `if (strpos($url, 'fonts.googleapis.com') === 8 || strpos($url, 'fonts.gstatic.com') === 8) {
`
So it should be impossible to use malformed URLs

**Comment by GenieTim** [comment]
Thanks. Yes, that makes it considerably more difficult. However, (1.) non-https fonts will not work anymore (not that they should), and (2.) for example:

https://fonts.your-domain.com/index.php?url=http://afonts.gstatic.com.my-malicious-url.com?... 

would still pass the check and provide the same attack as previously.
Here's one way that you could maybe fix things:

```php
function getHost($address)
{
	$parseUrl = parse_url(trim($address));
// if no protocol is given, we need this check here as the domain would be part of the path
	return trim($parseUrl['host'] ? $parseUrl['host'] : array_shift(explode('/', $parseUrl['path'], 2)));
}

// ...

if (in_array(getHost($url), [
		'fonts.googleapis.com', 'fonts.gstatic.com', 'www.gstatic.com',
	])) {
// load the stuff
}
```

in which case you rely on PHP's `parse_url` to be vulnerability-free rather than spinning your own things.
